// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl55ci0ghkM_vRhl1md0V49WLz3xmVJHY',
    appId: '1:151299344933:web:ccbbbe59c116786faecdcc',
    messagingSenderId: '151299344933',
    projectId: 'getx-9a993',
    authDomain: 'getx-9a993.firebaseapp.com',
    storageBucket: 'getx-9a993.appspot.com',
    measurementId: 'G-YXLLXRVKHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClWlHH3EuNEVyiMiY3xhv2L-HC9HjDN2k',
    appId: '1:151299344933:android:b02d2e8a7f02a239aecdcc',
    messagingSenderId: '151299344933',
    projectId: 'getx-9a993',
    storageBucket: 'getx-9a993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCG2Pw_FcZSBL2rImWKnf1AimCnzvSH5GI',
    appId: '1:151299344933:ios:66daefe618d969baaecdcc',
    messagingSenderId: '151299344933',
    projectId: 'getx-9a993',
    storageBucket: 'getx-9a993.appspot.com',
    iosBundleId: 'com.example.getxWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCG2Pw_FcZSBL2rImWKnf1AimCnzvSH5GI',
    appId: '1:151299344933:ios:a4b231b6aa653c87aecdcc',
    messagingSenderId: '151299344933',
    projectId: 'getx-9a993',
    storageBucket: 'getx-9a993.appspot.com',
    iosBundleId: 'com.example.getxWithFirebase.RunnerTests',
  );
}
